display_name: Hiddify
publisher_display_name: Hiddify
identity_name: app.hiddify.com
msix_version: 1.0.0.0
logo_path:  ..\..\assets\images\windows.ico
capabilities: internetClient, privateNetworkClientServer