name: Hiddify Next
description: A Proxy Frontend.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  slang: ^3.23.0
  slang_flutter: ^3.23.0
  recase: ^4.1.0
  timeago: ^3.5.0
  duration: ^3.0.13
  flutter_localized_locales: ^2.0.4

  # data & serialization
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # state management
  hooks_riverpod: ^2.3.8
  flutter_hooks: ^0.20.0
  riverpod_annotation: ^2.1.2
  rxdart: ^0.27.7

  # persistence
  drift: ^2.11.0
  sqlite3_flutter_libs: ^0.5.15
  shared_preferences: ^2.2.0

  # networking
  dio: ^5.3.2
  web_socket_channel: ^2.4.0

  # native
  ffi: ^2.1.0
  path_provider: ^2.1.0
  flutter_local_notifications: ^15.1.0+1
  mobile_scanner: ^3.4.1
  protocol_handler: ^0.1.5
  flutter_native_splash: ^2.3.2
  icons_launcher: ^2.1.3
  file_picker: ^5.3.3
  share_plus: ^7.1.0
  window_manager: ^0.3.5
  tray_manager: ^0.2.0
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.12

  # utils
  combine: ^0.5.4
  path: ^1.8.3
  loggy: ^2.0.3
  flutter_loggy: ^2.0.2
  meta: ^1.9.1
  stack_trace: ^1.11.0
  dartx: ^1.2.0
  uuid: ^3.0.7
  tint: ^2.0.1

  # widgets
  go_router: ^10.1.0
  flex_color_scheme: ^7.3.1
  flutter_animate: ^4.2.0+1
  flutter_svg: ^2.0.7
  gap: ^3.0.1
  percent_indicator: ^4.2.3
  fluttertoast: ^8.2.2
  sliver_tools: ^0.2.12
  flutter_adaptive_scaffold: ^0.1.6
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  riverpod_generator: ^2.2.6
  drift_dev: ^2.11.0
  ffigen: ^8.0.2
  slang_build_runner: ^3.23.0
  flutter_gen_runner: ^5.3.1
  go_router_builder: ^2.3.0
  custom_lint: ^0.5.2
  riverpod_lint: ^2.0.1

dependency_overrides:
  analyzer: '5.12.0'

flutter:
  uses-material-design: true
  assets:
    - assets/core/
    - assets/images/
  
  fonts:
    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam.ttf

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

icons_launcher:
  image_path: "assets/images/ic_launcher.png"
  platforms:
    android:
      enable: true
      adaptive_background_image: "assets/images/ic_launcher_background.png"
      adaptive_foreground_image: "assets/images/ic_launcher_foreground.png"
      adaptive_round_image: "assets/images/ic_launcher_round.png"
      adaptive_monochrome_image: "assets/images/ic_launcher_monochrome.png"
    windows:
      enable: true
      image_path: "assets/images/ic_launcher_round.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/ic_launcher.png
  android_12:
    image: assets/images/ic_launcher_foreground.png
    color: "#ffffff"

ffigen:
  name: 'SingboxNativeLibrary'
  description: 'Bindings to Singbox'
  output: 'lib/gen/singbox_generated_bindings.dart'
  headers:
    entry-points:
      - 'libcore/bin/libcore.h'