name: CI
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.vscode/'
      - 'appcast.xml'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.vscode/'
      - 'appcast.xml'

jobs:
  run:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions: write-all
    with:
      upload-artifact: false