name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'

      - name: Setup Go environment
        uses: actions/setup-go@v4.0.1

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Get Dependencies
        run: |
          make get

      - name: Generate
        run: |
          make gen
          make translate
          
      - name: Generate Libs
        run: |
          make android-libs windows-libs

      - name: Release Android
        run: |
          make release-android
          find ./ -type f -name "*.apk" -exec cp {} . \; 

      - name: Release Windows
        run: |
          flutter_distributor package --platform windows --targets exe
          find ./ -type f -name "*.exe" -exec cp {} . \; 

      - uses: actions/upload-artifact@v3
        with:
          name: apk
          path: ./*.apk

      - uses: actions/upload-artifact@v3
        with:
          name: exe
          path: ./*.exe
